services:
  server:
    build:
      tags:
        - registry.zaphiruz.me/server/commerce-galaxy-api-server:latest
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
